/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tarea3;

import java.math.BigDecimal;
import java.math.RoundingMode;
import java.util.Random;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author olste
 */
public class Principal extends javax.swing.JFrame {

    
    public String[] names = {"Oliver", "Carlos", "Maldo", "Denis", "Cristian", "Melvin", "Juan", "Isabel", "Jorge", "Abner"};
    public String [][] array = new String[10][5];
    
    
    public Principal() {
        initComponents();
        
        //custom table 1
        DefaultTableCellRenderer tcr = new DefaultTableCellRenderer();
        tcr.setHorizontalAlignment(SwingConstants.CENTER);
        jTable1.getColumnModel().getColumn(0).setCellRenderer(tcr);
        jTable1.getColumnModel().getColumn(1).setCellRenderer(tcr);
        jTable1.getColumnModel().getColumn(2).setCellRenderer(tcr);
        jTable1.getColumnModel().getColumn(3).setCellRenderer(tcr);
        jTable1.getColumnModel().getColumn(4).setCellRenderer(tcr);
        
        //custom table 2
        DefaultTableCellRenderer tcr2 = new DefaultTableCellRenderer();
        tcr2.setHorizontalAlignment(SwingConstants.CENTER);
        jTable3.getColumnModel().getColumn(0).setCellRenderer(tcr2);
        jTable3.getColumnModel().getColumn(1).setCellRenderer(tcr2);
        jTable3.getColumnModel().getColumn(2).setCellRenderer(tcr2);
        jTable3.getColumnModel().getColumn(3).setCellRenderer(tcr2);
        jTable3.getColumnModel().getColumn(4).setCellRenderer(tcr2);
        
        this.fillData();
    }

    
    public void fillData(){
        this.fillNames();
        this.fillNotes();
        this.fillProm();
        this.FillTable();
        this.FillTable2();
    }
    
    
    public int getPosition(){
        double mayor = 0;
        int pos = 0;
        for(int i = 0; i < 10; i++){
            if(Double.valueOf(this.array[i][4]) > mayor)
            {
                mayor = Double.valueOf(this.array[i][4]);
                pos = i;
            }
        }
        return pos;
    }
    
    
    
    
    
    public void FillTable(){
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        model.setRowCount(0);
        for(int i = 0; i < 10; i++){
            Object[] row = {this.array[i][0], this.array[i][1], this.array[i][2], this.array[i][3], this.array[i][4]};              
            model.addRow(row);
        }
    }
    
    
    public void FillTable2(){
        
        //custom
        
        
        
        
        DefaultTableModel model2 = (DefaultTableModel)jTable3.getModel();
        model2.setRowCount(0);
        int pos = this.getPosition();
        System.out.println(pos);
        Object[] ro2 = {this.array[pos][0], this.array[pos][1], this.array[pos][2], this.array[pos][3], this.array[pos][4]};              
        model2.addRow(ro2);
    }
    
    
    public void fillNames(){
        for(int i = 0; i < 10; i++){
            this.array[i][0] = this.names[i];
        }
    }
    
    
    public void fillNotes(){
        for(int i = 1; i < 4; i++){
            for(int j = 0; j < 10; j++){
                double leftLimit = 0.00;
                double rightLimit = 100.00;
                double generatedDouble = leftLimit + new Random().nextDouble() * (rightLimit - leftLimit);
                BigDecimal bd = new BigDecimal(generatedDouble).setScale(2, RoundingMode.HALF_UP);
                double val2 = bd.doubleValue();
                this.array[j][i] = Double.toString(val2);
            }
        }
    }
    
    public double getProm(double n1, double n2, double n3){
        return (n1+n2+n3)/3;
    }
    
    
    
    public void fillProm(){
        for(int i = 0; i < 10; i++){
            double n1 = Double.valueOf(this.array[i][1]);
            double n2 = Double.valueOf(this.array[i][2]);
            double n3 = Double.valueOf(this.array[i][3]);
            double r = this.getProm(n1, n2, n3);
            BigDecimal bd = new BigDecimal(r).setScale(2, RoundingMode.HALF_UP);
            double val2 = bd.doubleValue();
            this.array[i][4] = Double.toString(val2);
        }
    }
    
    
    
    
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aplication");
        setLocation(new java.awt.Point(300, 200));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Prueba 1", "Prueba 2", "Prueba 3", "Promedio"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Prueba 1", "Prueba 2", "Prueba 3", "Promedio"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTable3);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Promedio mas Alto");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1)
                            .addComponent(jScrollPane3)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(279, 279, 279)
                        .addComponent(jLabel1)))
                .addContainerGap(145, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    // End of variables declaration//GEN-END:variables
}
